### ISSUE TITLE
`std::fmt::Display` not implemented

### ISSUE THREAD

**Issue by uzyn** [paritytech/bigint#31]
Even with the sample code provided at README.md.

It's getting the following error:

```
`bigint::U256` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
   |
   = help: the trait `std::fmt::Display` is not implemented for `bigint::U256`
   = note: required by `std::fmt::Display::fmt`
```

**Comment by NikVolf** [comment]
you probably use it with `default-features = false`?

**Comment by uzyn** [comment]
This is how it looks on my Cargo.toml

```toml
bigint = "4.2.0"
```

How do I enable default features?

**Comment by NikVolf** [comment]
replace your line with
```
bigint = { version = "4.0", features = ["std"] }
```

as a workaround

we will update docs/configs

**Comment by uzyn** [comment]
Thanks. That works!

**Comment by NikVolf** [comment]
will keep it open until `std` feature will be default

**Comment by Pzixel** [comment]
Hey guys.

Why does `Display` is not implemented for `no_std` environments? Why there are these artificial limitations?

**Comment by debris** [comment]
no reason. fix should be trivial, just change feature gates and replace `std::fmt::Display` with `core::fmt::Display`. PRs are welcomed :)
